name: Run Formatters and Linters

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v4
      - name: Enable Corepack for `pnpm`
        run: corepack enable pnpm
      - name: Get `pnpm` Store Directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup `pnpm` Cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install
      - name: Check Formatting
        run: pnpm fmt
      - name: Check HTML
        run: pnpm lint:html
      - name: Check CSS
        run: pnpm lint:css
      - name: Synchronize SvelteKit
        run: pnpm sync
      - name: Check Svelte
        run: pnpm lint:svelte
      - name: Check JavaScript
        run: pnpm lint:js
